# Generated by Django 3.0.8 on 2020-07-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=512, verbose_name='name')),
                ('second_name', models.CharField(blank=True, max_length=512, verbose_name='second name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='дата создания')),
                ('name', models.CharField(blank=True, max_length=512, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('img', models.CharField(blank=True, max_length=32, verbose_name='фото')),
                ('price', models.IntegerField(default=999, verbose_name='цена')),
                ('level', models.CharField(choices=[('e', 'Easy'), ('n', 'Normal'), ('h', 'Hard')], default='e', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Author')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='author',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag'),
        ),
    ]
